# Generated by Django 4.1.2 on 2022-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('last_names', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('first_names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('identification', models.CharField(max_length=13, verbose_name='Cédula')),
                ('cellphone', models.CharField(max_length=15, verbose_name='Celular')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=150)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
